### ISSUE TITLE
skychunk.ini is reset on each load

### ISSUE THREAD

**Issue by LucilleTea** [Boundarybreaker/Skychunk#3]
Each time the game is loaded skychunk.ini is regenerated completely, including the commented timestamp. Since there's no in-game way to edit the setting, it seems like this prevents it from being edited at all.
This happens with no other mods loaded, using fabric loader 0.11.3, java 15, minecraft 1.16.5 and skychunk 1.1.0.

I think I've already told you anything interesting in the log, [but here it is anyway](https://paste.ee/p/IYblt).

**Comment by LemmaEOF** [comment]
.....uh,

**Comment by LemmaEOF** [comment]
why is this not working what

**Comment by LemmaEOF** [comment]
apparently properties sucks, 1.1.1 should *hopefully* fix it

**Comment by LucilleTea** [comment]
Tested the fabric one and it works perfectly! Thanks!

**Comment by LemmaEOF** [comment]
よかったー
